baseurl = "https://raphapr.github.io"
title = "Raphael P. R."
author = "Raphael P. R."
canonifyurls = true
paginate = 5

theme = "strange-case"

[params]
	colorScheme = "scheme-darkbrown"
	DateFormat = "2 Jan 2006"
    description = "Cloud Engineering"
	sidebarFreeText = "A small corner of the internet which I just talk about everything I learned recently"

[[menu.main]]
	name = "github"
	url = "https://github.com/raphapr"

[[menu.main]]
	name = "LinkedIn"
	url = "https://www.linkedin.com/in/raphaelpr/"

[[menu.main]]
	name = "Email"
	url = "mailto:raphaelpr01@gmail.com"
